# -*- coding:utf-8 -*-
# PROJECT_NAME : django-super-cache
# FILE_NAME    : 
# AUTHOR       : younger shen

DJANGO_SUPER_CACHE_ENABLED = False

DJANGO_SUPER_CACHE_BACKEND = 'file'

DJANGO_SUPER_CACHE_EXPIRE_TIME = 24

DJANGO_SUPER_CACHE_AUTO_UPDATE = True

DJANGO_SUPER_CACHE_FILE_DIR = '/var/cache/'
